module.exports = [
  {
    marca: "Ford",
    modelo: "Fiesta",
    color: "Azul",
    año: 2019,
    km: 200,
    precio: 120000,
    cuotas: 12,
    patente: "APL123",
    vendido: false,
  },
  {
    marca: "Toyota",
    modelo: "Corolla",
    color: "Blanco",
    año: 2019,
    km: 0,
    precio: 150000,
    cuotas: 14,
    patente: "JJK116",
    vendido: false,
  },
  {
    marca: "Toyota",
    modelo: "Yaris",
    color: "blanco",
    año: 2022,
    km: 20,
    precio: 200000,
    cuotas: 24,
    patente: "FFF030",
    vendido: false,
  },
];
